export const BUSINESS = {
  name: 'Master Auto Mechanic',
  phone: '(718) 555-0000',
  phoneHref: 'tel:+17185550000',
  address: {
    street: '20 Giffords Glen',
    city: 'Staten Island',
    state: 'NY',
    zip: '10308',
    full: '20 Giffords Glen, Staten Island, NY 10308',
    mapsUrl: 'https://maps.google.com/?q=20+Giffords+Glen+Staten+Island+NY+10308',
  },
  hours: [
    { days: 'Monday – Friday', hours: '8:00 AM – 6:00 PM', open: true },
    { days: 'Saturday', hours: '8:00 AM – 3:00 PM', open: true },
    { days: 'Sunday', hours: 'Closed', open: false },
  ],
  services: [
    { name: 'Engine Diagnostics', icon: 'cpu', description: 'Pinpoint engine issues fast with professional diagnostic equipment. We read the codes and tell you exactly what your vehicle needs.' },
    { name: 'NY State Inspection', icon: 'clipboard-check', description: 'Certified New York State inspections performed quickly and thoroughly. Get your sticker and get back on the road.' },
    { name: 'Brake Service', icon: 'disc', description: 'Full brake inspections, pad replacement, rotor resurfacing and replacement. Drive with confidence knowing your brakes are right.' },
    { name: 'Oil Change', icon: 'droplets', description: 'Fast, clean oil and filter changes using the right oil for your vehicle. Includes a basic vehicle check.' },
    { name: 'A/C Repair', icon: 'wind', description: 'Diagnose and repair air conditioning issues. Refrigerant recharge, compressor service, and leak repair.' },
    { name: 'Tire Service', icon: 'circle-dot', description: 'Flat tire repair, tire rotation, and tire replacement. We get you back rolling safely.' },
    { name: 'Radiator Flush', icon: 'thermometer', description: 'Coolant system flush and fill to prevent overheating and extend engine life.' },
    { name: 'Transmission Service', icon: 'settings', description: 'Transmission fluid service, filter replacement, and diagnostics for automatic and manual transmissions.' },
    { name: 'Tune-Up & Maintenance', icon: 'wrench', description: 'Spark plugs, filters, belts, and fluids. Routine maintenance that keeps your vehicle running at its best.' },
    { name: 'General Auto Repair', icon: 'car', description: 'Comprehensive repairs for most makes and models. If something is wrong, call us — we handle it.' },
  ],
  testimonials: [
    { name: 'Mike D.', rating: 5, text: 'Brought my car in for brakes and an inspection. Fast, honest pricing, no surprises. Will be back.' },
    { name: 'Lisa R.', rating: 5, text: 'Best mechanic on Staten Island. They explained everything clearly and the price was fair. Highly recommend.' },
    { name: 'Tony S.', rating: 5, text: 'My whole family uses Master Auto. Reliable, experienced, and they actually stand behind their work.' },
    { name: 'Karen M.', rating: 5, text: 'Needed an emergency repair and they fit me in same day. Great service, great people.' },
  ],
  nav: [
    { label: 'Home', path: '/' },
    { label: 'Services', path: '/services' },
    { label: 'About', path: '/about' },
    { label: 'Contact', path: '/contact' },
  ],
} as const
